# Generated by Django 3.2.9 on 2022-04-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('sizes', models.CharField(max_length=100)),
                ('cloth_width', models.CharField(max_length=100)),
                ('cloth', models.CharField(max_length=100)),
                ('dublerin_cons', models.CharField(max_length=100)),
                ('flizelin_cons', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('furniture', models.TextField()),
                ('proccesing', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.model')),
            ],
            options={
                'verbose_name': 'Фото модели',
                'verbose_name_plural': 'Фото модели',
            },
        ),
    ]
