# Generated by Django 3.2.9 on 2022-04-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20220419_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='field1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
