# Generated by Django 3.2.9 on 2022-04-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20220427_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='cloth_cons_comm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='cloth_cons_fact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='cloth_width',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='dublerin_cons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='flizelin_cons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
